functional:
  - Пользователь может просматривать каталог товаров с постраничным выводом
  - Пользователь может просматривать подробную информацию о товаре на отдельной странице
  - Пользователь может искать товары по ключевому слову или категории
  - Пользователь может фильтровать товары по заданным параметрам
  - Пользователь может добавлять товары в корзину
  - Пользователь может удалять товары из корзины
  - Пользователь может просматривать содержимое корзины
  - Пользователь может оформить заказ и перейти на страницу оплаты
  - Пользователь может продолжать выбирать товары в каталоге после добавления в корзину
  - Пользователь может переключать язык интерфейса
  - Сайт поддерживает локализацию на русском и английском языках
  - Корзина сохраняется в сессии браузера

non-functional:
  - Сайт должен быть адаптивным и удобным на мобильных устройствах
  - Сайт должен быть SPA (одностраничным приложением) без перезагрузки страницы
  - Сайт должен быть оптимизирован для высокой скорости работы
  - Сайт должен быть безопасным и защищать персональные данные пользователя
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен уметь обрабатывать большое количество трафика

implicit:
  - Пользователь должен видеть название, рейтинг, цену и скидку на товар в каталоге и на странице товара
  - Интерфейс должен быть интуитивно понятным и удобным в использовании
  - Ошибка при добавлении товара в корзину должна отображаться пользователю
  - Должна быть визуальная обратная связь при добавлении товара в корзину (например, уведомление или изменение иконки)
  - После оформления заказа пользователь должен получить подтверждение
  - Данные о товарах должны загружаться асинхронно (через API)
