---
functional:
  - Пользователь может просматривать каталог товаров с разбивкой по категориям (телефоны, ноутбуки, аксессуары и т.д.)
  - Пользователь может искать товары по ключевому слову в поисковой строке
  - Пользователь может фильтровать товары по цене, рейтингу, наличию и другим параметрам
  - Пользователь может добавлять товары в корзину и изменять их количество
  - Пользователь может удалять товары из корзины
  - Система отображает актуальную стоимость заказа с учётом скидок
  - Пользователь может оформить заказ, указав контактные данные и способ доставки
  - Система сохраняет содержимое корзины в локальной сессии браузера
  - Пользователь может переключаться между языками интерфейса (русский/английский)
  - Система отображает подробную страницу товара с фото, описанием, ценой и рейтингом
  - Пользователь может просматривать историю своих заказов в личном кабинете
  - Система позволяет отменить заказ до его обработки


non-functional:
  - Сайт загружается не более 3 секунд при стабильном интернет‑соединении
  - Интерфейс адаптирован для экранов от 320px до 1920px
  - Все формы ввода имеют валидацию и подсказки при ошибках
  - Система обрабатывает до 1000 одновременных запросов без потери производительности
  - Данные пользователей шифруются при передаче (HTTPS)
  - Поиск реагирует на ввод в реальном времени (не более 500 мс задержки)
  - Изображения товаров оптимизированы для быстрой загрузки (не более 200 КБ)
  - Система поддерживает последние версии Chrome, Firefox, Safari и Edge
  - Тексты локализованы без грамматических ошибок и обрезаний
  - Страницы доступны для скринридеров (базовая доступность)


implicit:
  - При отсутствии товаров по фильтру отображается сообщение «Товары не найдены»
  - Корзина сохраняет состояние при перезагрузке страницы
  - Поисковая строка очищает ввод по кнопке «×»
  - Поля форм подсвечиваются красным при неверном вводе
  - Кнопки меняют состояние при наведении (визуальная обратная связь)
  - Ссылки на внешние ресурсы открываются в новой вкладке
  - Система автоматически выходит из сессии через 30 минут бездействия
  - Сообщения об ошибках содержат рекомендации по исправлению
  - Изображения имеют alt‑тексты для SEO и доступности
  - Форма оплаты поддерживает карты Visa/MasterCard/МИР
  - После оформления заказа пользователь получает email‑подтверждение
